// src/utils/nations.js
// Lista amplia (no exhaustiva) de países ISO-2 para combos.
const nations = [
    // Américas
    { code: "AR", name: "Argentina" },
    { code: "BO", name: "Bolivia" },
    { code: "BR", name: "Brasil" },
    { code: "CL", name: "Chile" },
    { code: "CO", name: "Colombia" },
    { code: "CR", name: "Costa Rica" },
    { code: "CU", name: "Cuba" },
    { code: "DO", name: "República Dominicana" },
    { code: "EC", name: "Ecuador" },
    { code: "GT", name: "Guatemala" },
    { code: "HN", name: "Honduras" },
    { code: "MX", name: "México" },
    { code: "NI", name: "Nicaragua" },
    { code: "PA", name: "Panamá" },
    { code: "PY", name: "Paraguay" },
    { code: "PE", name: "Perú" },
    { code: "PR", name: "Puerto Rico" },
    { code: "SV", name: "El Salvador" },
    { code: "UY", name: "Uruguay" },
    { code: "VE", name: "Venezuela" },
    { code: "CA", name: "Canadá" },
    { code: "US", name: "Estados Unidos" },
  
    // Europa
    { code: "AL", name: "Albania" },
    { code: "AT", name: "Austria" },
    { code: "BE", name: "Bélgica" },
    { code: "BG", name: "Bulgaria" },
    { code: "CH", name: "Suiza" },
    { code: "CY", name: "Chipre" },
    { code: "CZ", name: "Chequia" },
    { code: "DE", name: "Alemania" },
    { code: "DK", name: "Dinamarca" },
    { code: "EE", name: "Estonia" },
    { code: "ES", name: "España" },
    { code: "FI", name: "Finlandia" },
    { code: "FR", name: "Francia" },
    { code: "GB", name: "Reino Unido" },
    { code: "GR", name: "Grecia" },
    { code: "HR", name: "Croacia" },
    { code: "HU", name: "Hungría" },
    { code: "IE", name: "Irlanda" },
    { code: "IS", name: "Islandia" },
    { code: "IT", name: "Italia" },
    { code: "LT", name: "Lituania" },
    { code: "LU", name: "Luxemburgo" },
    { code: "LV", name: "Letonia" },
    { code: "MT", name: "Malta" },
    { code: "NL", name: "Países Bajos" },
    { code: "NO", name: "Noruega" },
    { code: "PL", name: "Polonia" },
    { code: "PT", name: "Portugal" },
    { code: "RO", name: "Rumania" },
    { code: "RS", name: "Serbia" },
    { code: "SE", name: "Suecia" },
    { code: "SI", name: "Eslovenia" },
    { code: "SK", name: "Eslovaquia" },
    { code: "UA", name: "Ucrania" },
  
    // África
    { code: "DZ", name: "Argelia" },
    { code: "EG", name: "Egipto" },
    { code: "MA", name: "Marruecos" },
    { code: "NG", name: "Nigeria" },
    { code: "ZA", name: "Sudáfrica" },
    { code: "KE", name: "Kenia" },
    { code: "ET", name: "Etiopía" },
    { code: "TN", name: "Túnez" },
    { code: "GH", name: "Ghana" },
    { code: "CI", name: "Costa de Marfil" },
  
    // Asia y Oceanía
    { code: "AE", name: "Emiratos Árabes Unidos" },
    { code: "AU", name: "Australia" },
    { code: "BD", name: "Bangladés" },
    { code: "CN", name: "China" },
    { code: "HK", name: "Hong Kong" },
    { code: "ID", name: "Indonesia" },
    { code: "IL", name: "Israel" },
    { code: "IN", name: "India" },
    { code: "JP", name: "Japón" },
    { code: "KR", name: "Corea del Sur" },
    { code: "MY", name: "Malasia" },
    { code: "NZ", name: "Nueva Zelanda" },
    { code: "PH", name: "Filipinas" },
    { code: "PK", name: "Pakistán" },
    { code: "QA", name: "Catar" },
    { code: "SA", name: "Arabia Saudita" },
    { code: "SG", name: "Singapur" },
    { code: "TH", name: "Tailandia" },
    { code: "TR", name: "Turquía" },
    { code: "TW", name: "Taiwán" },
    { code: "VN", name: "Vietnam" },
  ];
  
  export default nations;
  